'use strict';

const { contextBridge, ipcRenderer } = require('electron');
// Sandboxed preload scripts cannot require application files. This literal is
// checked against shared/ipc-channels.js by test/ipc-contract.js.
const IPC = Object.freeze({
  PET_EVENT: 'pet:event', PET_STATS: 'pet:stats', PANEL_STATS: 'panel:stats', PANEL_PRICE: 'panel:price',
  GET_STATS: 'get-stats', GET_WIN_POS: 'get-win-pos', GET_WINDOW_METRICS: 'get-window-metrics',
  XIABAN_SCHEDULE: 'xiaban:schedule',
  PET_ASSETS: 'pet-assets:changed',
  UPDATE_STATE: 'update:state',
  PRIVACY_STATE: 'privacy:state',
  COMPANION_STATE: 'companion:state', GET_COMPANION_STATE: 'companion:get-state',
  WORKFLOW_PREFERENCES: 'workflow:preferences', WORKFLOW_COMMAND: 'workflow:command',
  GET_WORKFLOW_PREFERENCES: 'workflow:get-preferences', SET_WORKFLOW_PREFERENCES: 'workflow:set-preferences',
  UPDATE_SESSION_PREFERENCES: 'workflow:update-session', MARK_RECENT_READ: 'workflow:mark-read',
  CLEAR_RECENT: 'workflow:clear-recent', FOCUS_RECENT: 'workflow:focus-recent',
  SET_COMPANION_PREFS: 'companion:set-preferences', REST_ACTION: 'rest:action', OPEN_HIDE_MENU: 'pet:hide-menu',
  GET_UPDATE_STATE: 'update:get-state', CHECK_FOR_UPDATES: 'update:check', SET_AUTO_UPDATE: 'update:set-auto',
  DOWNLOAD_UPDATE: 'update:download', INSTALL_UPDATE: 'update:install', OPEN_UPDATE_PAGE: 'update:open-page',
  SET_WIN_POS: 'set-win-pos', END_WIN_DRAG: 'end-win-drag', OPEN_PANEL: 'open-panel', CLOSE_PANEL: 'close-panel',
  GET_AUTO_LAUNCH: 'get-auto-launch', SET_AUTO_LAUNCH: 'set-auto-launch',
  GET_PRIVACY_MODE: 'privacy:get', SET_PRIVACY_MODE: 'privacy:set',
  GET_CHIP_DISPLAY: 'chip:get-display', SET_CHIP_DISPLAY: 'chip:set-display',
  GET_INTEGRATION_HEALTH: 'integrations:get-health', REPAIR_INTEGRATIONS: 'integrations:repair',
  UNINSTALL_INTEGRATIONS: 'integrations:uninstall',
  GET_XIABAN_SCHEDULE: 'get-xiaban-schedule', SET_XIABAN_SCHEDULE: 'set-xiaban-schedule',
  GET_PET_ASSETS: 'get-pet-assets', IMPORT_PET_GIF: 'import-pet-gif',
  REMOVE_PET_ASSET: 'remove-pet-asset', RESET_PET_SLOT: 'reset-pet-slot',
  SELECT_PET_CHARACTER: 'pet-character:select', CREATE_PET_CHARACTER: 'pet-character:create',
  IMPORT_PET_CHARACTER: 'pet-character:import', REMOVE_PET_CHARACTER: 'pet-character:remove',
  OPEN_SETTINGS: 'open-settings', CLOSE_SETTINGS: 'close-settings',
  SET_PANEL_HEIGHT: 'set-panel-height', CLOSE_PET: 'close-pet',
  PERMISSION_DECIDE: 'permission-decide', FOCUS_SESSION: 'focus-session', SET_PET_SIZE: 'set-pet-size',
  PET_BLUR: 'pet-blur', PET_POINTER_CHECK: 'pet:pointer-check', SET_IGNORE_MOUSE: 'set-ignore-mouse', QUOTA_ALERT_SHOWN: 'quota-alert:shown',
});

contextBridge.exposeInMainWorld('pet', {
  onWorkflowPreferences: cb => ipcRenderer.on(IPC.WORKFLOW_PREFERENCES, (_e, value) => cb(value)),
  onWorkflowCommand: cb => ipcRenderer.on(IPC.WORKFLOW_COMMAND, (_e, value) => cb(value)),
  getWorkflowPreferences: () => ipcRenderer.invoke(IPC.GET_WORKFLOW_PREFERENCES),
  setWorkflowPreferences: value => ipcRenderer.invoke(IPC.SET_WORKFLOW_PREFERENCES, value),
  updateSessionPreferences: (id, value) => ipcRenderer.invoke(IPC.UPDATE_SESSION_PREFERENCES, id, value),
  markRecentRead: ids => ipcRenderer.invoke(IPC.MARK_RECENT_READ, ids),
  clearRecent: () => ipcRenderer.invoke(IPC.CLEAR_RECENT),
  focusRecent: id => ipcRenderer.invoke(IPC.FOCUS_RECENT, id),
  // 主进程 -> 渲染进程
  onEvent: (cb) => ipcRenderer.on(IPC.PET_EVENT, (_e, data) => cb(data)),
  onStats: (cb) => ipcRenderer.on(IPC.PET_STATS, (_e, data) => cb(data)),
  onPanelStats: (cb) => ipcRenderer.on(IPC.PANEL_STATS, (_e, data) => cb(data)),
  onPrice: (cb) => ipcRenderer.on(IPC.PANEL_PRICE, (_e, data) => cb(data)),
  onXiabanSchedule: (cb) => ipcRenderer.on(IPC.XIABAN_SCHEDULE, (_e, data) => cb(data)),
  onPetAssets: (cb) => ipcRenderer.on(IPC.PET_ASSETS, (_e, data) => cb(data)),
  onUpdateState: (cb) => ipcRenderer.on(IPC.UPDATE_STATE, (_e, data) => cb(data)),
  onPrivacyMode: (cb) => ipcRenderer.on(IPC.PRIVACY_STATE, (_e, data) => cb(data)),
  onCompanionState: (cb) => ipcRenderer.on(IPC.COMPANION_STATE, (_e, data) => cb(data)),
  onPointerCheck: (cb) => ipcRenderer.on(IPC.PET_POINTER_CHECK, (_e, point) => cb(point)),
  getCompanionState: () => ipcRenderer.invoke(IPC.GET_COMPANION_STATE),
  setCompanionPreferences: (value) => ipcRenderer.invoke(IPC.SET_COMPANION_PREFS, value),
  restAction: (value) => ipcRenderer.invoke(IPC.REST_ACTION, value),
  openHideMenu: () => ipcRenderer.send(IPC.OPEN_HIDE_MENU),
  // 渲染进程 -> 主进程
  getStats: () => ipcRenderer.invoke(IPC.GET_STATS),
  openPanel: (agent) => ipcRenderer.send(IPC.OPEN_PANEL, agent || 'all'),
  openSettings: () => ipcRenderer.send(IPC.OPEN_SETTINGS),
  closePanel: () => ipcRenderer.send(IPC.CLOSE_PANEL),
  getAutoLaunch: () => ipcRenderer.invoke(IPC.GET_AUTO_LAUNCH),
  setAutoLaunch: (enabled) => ipcRenderer.invoke(IPC.SET_AUTO_LAUNCH, !!enabled),
  getPrivacyMode: () => ipcRenderer.invoke(IPC.GET_PRIVACY_MODE),
  getChipDisplay: () => ipcRenderer.invoke(IPC.GET_CHIP_DISPLAY),
  setChipDisplay: (value) => ipcRenderer.invoke(IPC.SET_CHIP_DISPLAY, value),
  setPrivacyMode: (enabled) => ipcRenderer.invoke(IPC.SET_PRIVACY_MODE, !!enabled),
  getIntegrationHealth: () => ipcRenderer.invoke(IPC.GET_INTEGRATION_HEALTH),
  repairIntegrations: () => ipcRenderer.invoke(IPC.REPAIR_INTEGRATIONS),
  uninstallIntegrations: () => ipcRenderer.invoke(IPC.UNINSTALL_INTEGRATIONS),
  getXiabanSchedule: () => ipcRenderer.invoke(IPC.GET_XIABAN_SCHEDULE),
  setXiabanSchedule: (schedule) => ipcRenderer.invoke(IPC.SET_XIABAN_SCHEDULE, schedule),
  getPetAssets: () => ipcRenderer.invoke(IPC.GET_PET_ASSETS),
  importPetGif: (slotId, mode, options) => ipcRenderer.invoke(IPC.IMPORT_PET_GIF, slotId, mode, options || {}),
  removePetAsset: (slotId, assetId) => ipcRenderer.invoke(IPC.REMOVE_PET_ASSET, slotId, assetId),
  resetPetSlot: (slotId) => ipcRenderer.invoke(IPC.RESET_PET_SLOT, slotId),
  selectPetCharacter: (id) => ipcRenderer.invoke(IPC.SELECT_PET_CHARACTER, id),
  createPetCharacter: (name, options) => ipcRenderer.invoke(IPC.CREATE_PET_CHARACTER, name, options || {}),
  importPetCharacter: () => ipcRenderer.invoke(IPC.IMPORT_PET_CHARACTER),
  removePetCharacter: (id) => ipcRenderer.invoke(IPC.REMOVE_PET_CHARACTER, id),
  getUpdateState: () => ipcRenderer.invoke(IPC.GET_UPDATE_STATE),
  checkForUpdates: () => ipcRenderer.invoke(IPC.CHECK_FOR_UPDATES),
  setAutoUpdate: (enabled) => ipcRenderer.invoke(IPC.SET_AUTO_UPDATE, !!enabled),
  downloadUpdate: () => ipcRenderer.invoke(IPC.DOWNLOAD_UPDATE),
  installUpdate: () => ipcRenderer.invoke(IPC.INSTALL_UPDATE),
  openUpdatePage: () => ipcRenderer.invoke(IPC.OPEN_UPDATE_PAGE),
  closeSettings: () => ipcRenderer.send(IPC.CLOSE_SETTINGS),
  // 单宠模式：收起唯一的一只打工伙伴。
  closePet: () => ipcRenderer.send(IPC.CLOSE_PET),
  // 手动拖动窗口
  getWinPos: () => ipcRenderer.invoke(IPC.GET_WIN_POS),
  getWindowMetrics: () => ipcRenderer.invoke(IPC.GET_WINDOW_METRICS),
  setWinPos: (x, y, dragOffset) => ipcRenderer.send(IPC.SET_WIN_POS, x, y, dragOffset || null),
  endWinDrag: (dragId) => ipcRenderer.send(IPC.END_WIN_DRAG, dragId),
  // 原生授权：通过本地 HTTP server 回 CC 决策（allow/deny），不需按键/Accessibility
  decidePermission: (permId, behavior) => ipcRenderer.invoke(IPC.PERMISSION_DECIDE, permId, behavior),
  // 对话类（继续/选择/方案）：Codex 精确打开对应 task，其它 Agent 定位会话窗口/终端
  focusSession: (sessionId) => ipcRenderer.invoke(IPC.FOCUS_SESSION, sessionId),
  // 透明空白处点击穿透：渲染端命中测试后切换（true=穿透，鼠标事件仍转发回来）
  setIgnoreMouse: (ignore) => ipcRenderer.send(IPC.SET_IGNORE_MOUSE, ignore),
  quotaAlertShown: (alertIds) => ipcRenderer.send(IPC.QUOTA_ALERT_SHOWN, alertIds),
  // 按弹层内容精确定高（动态，避免固定大窗口留白）；w/h<=0 复位
  setPetSize: (w, h, anchor, mode) => ipcRenderer.send(IPC.SET_PET_SIZE, w, h, anchor, mode),
  // 详情面板按内容高度自适应，避免底部留白 / 内容多时被切
  setPanelHeight: (h) => ipcRenderer.send(IPC.SET_PANEL_HEIGHT, h),
  // 输入框结束后归还窗口焦点
  blurPet: () => ipcRenderer.send(IPC.PET_BLUR),
  // 上报「用户正在交互」(选项面板/右键菜单/记事本)——领地模式据此避战/撤退
});
